apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-list-events
---
---
# kubectl --as=system:serviceaccount:prom:sa-list-events auth can-i get events
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-events-to-sa
roleRef:
  kind: ClusterRole
  name: list-events
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sa-list-events
  namespace: prom
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: list-events
rules: 
- apiGroups: [""]
  resources: ["events"] 
  verbs: ["get", "watch", "list"]
---
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fred-logs
spec:
  replicas: 1
  selector:
   matchLabels:
      app: fred-logs
  template:
    metadata:
      name: fred-logs
      labels:
        app: fred-logs
    spec:
      serviceAccountName: sa-list-events
      containers:
      - name: fred-logs
        command:
        - /bin/bash
        - -c
        - |
          kubectl get events -A --watch --output=json
        image: bitnami/kubectl
        imagePullPolicy: IfNotPresent
      nodeSelector:
        role: workers
        kubernetes.io/os: linux