apiVersion: apps/v1
kind: Deployment
metadata:
  name: theia
  namespace: default
spec:
  selector:
    matchLabels:
      app: theia
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: theia
    spec:
      volumes:
      - name: data
        hostPath:
          path: /home/sourceCode # this folder must be exposed in read and write 755
      containers:
      - name: theia
        volumeMounts:
        - name: data 
          mountPath: "/home/project"
        image: theiaide/theia
        ports:
        - containerPort: 3000
---
---
apiVersion: v1
kind: Service
metadata:
  name: theia-service
  labels:
    run: theia-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30005
    name: ide-port
  selector:
    app: theia
  type: NodePort

