apiVersion: apps/v1
kind: Deployment
metadata:
  name: statping
  namespace: default
spec:
  selector:
    matchLabels:
      app: statping
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: statping
    spec:
      containers:
      - name: statping
        image: statping/statping
        ports:
        - containerPort: 8080
      nodeName: filibfrdpfdck02
---
---
apiVersion: v1
kind: Service
metadata:
  name: statping-service
  labels:
    run: statping-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30025
    name: ide-port
  selector:
    app: statping
  type: NodePort

