# APPLICATION
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1 
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-alpine
        image: mysql:5.6
        ports:
        - containerPort: 3306
          protocol: TCP
          name: nginx
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
          name: init-sql-config
        - mountPath: /var/lib/mysql
          name: mysql-data
      volumes:
      - name: init-sql-config
        configMap:
          name: sql-config
      - name: mysql-data
        emptyDir:
         sizeLimit: 1G

