apiVersion: v1
kind: Service
metadata:
  name: openssh-service
  namespace: iorb
spec:
  type: ClusterIP
  selector:
    app: openssh
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22

