# kubectl --as=system:serviceaccount:$namespace:sa-secret-creation auth can-i get events
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-secret-creation
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-creation-to-sa
roleRef:
  kind: ClusterRole
  name: secret-creation
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sa-secret-creation
  namespace: $namespace                 #  <<----  !!! specify the namespace you will deploy to 
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: secret-creation
rules: 
- apiGroups: ["*"]
  resources: ["secrets"] 
  verbs: ["*"]
